# KEGG analysis
Sys.setenv(LANGUAGE = "en") 
options(stringsAsFactors = FALSE) 
options(clusterProfiler.download.method = "wininet")
library(DOSE)
library(GO.db)
library(org.Hs.eg.db)
library(topGO)
library(GSEABase)
library(clusterProfiler)
library(enrichplot)
library(ggplot2)
library(ggThemeAssist)
library(stringr)
library(KEGG.db)
set.seed(1)
gene1<-read.table("gene_40.txt",header=F)
symbol1=as.character(gene1[,1])
eg1 = bitr(symbol1, fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Hs.eg.db")
kk <- enrichKEGG(gene = eg1$ENTREZID,organism = 'hsa',pvalueCutoff = 0.05,pAdjustMethod = "BH", qvalueCutoff = 1)
a = dotplot(kk,showCategory=15,title="KEGG pathway")
ek_kk <- setReadable(kk,OrgDb = org.Hs.eg.db, keyType = "ENTREZID")
ek_kk <- as.data.frame(ek_kk)
write.csv(ek_kk, file = "kegg.csv", quote=F, row.names=T)
